import { chromium } from 'playwright-core';

const browser = await chromium.launch({
  executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  headless: true,
});
const results = { consoleErrors: [], pageErrors: [], failedRequests: [] };
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 1 });
const baseUrl = process.env.QA_URL || 'http://127.0.0.1:5173/';
page.on('console', (message) => { if (message.type() === 'error') results.consoleErrors.push(message.text()); });
page.on('pageerror', (error) => results.pageErrors.push(error.message));
page.on('requestfailed', (request) => results.failedRequests.push(`${request.url()} — ${request.failure()?.errorText}`));
const waitForAnalytics = async () => {
  await page.waitForTimeout(900);
  await page.locator('.loading-block').waitFor({ state: 'detached', timeout: 180000 });
};
await page.goto(baseUrl, { waitUntil: 'domcontentloaded', timeout: 180000 });
await page.waitForTimeout(25000);
await waitForAnalytics();
await page.screenshot({ path: 'qa-desktop.png', fullPage: false });
results.title = await page.title();
results.status = await page.locator('.status-button').textContent().catch(() => null);
results.logoLink = await page.locator('.brand-link').getAttribute('href');
results.defaultLayerStates = await page.locator('.toggle-row').evaluateAll((nodes) => nodes.map((node) => ({ label: node.innerText.split('\n')[0], enabled: node.getAttribute('aria-pressed') })));
results.defaultPerformance = await page.locator('.performance-total').first().innerText();
results.defaultTable = await page.locator('.drawer-handle').innerText();
results.selectionTools = await page.locator('.selection-tools').innerText();
results.basemapGalleryCount = await page.locator('.esri-basemap-gallery').count();
await page.locator('.selection-tools button[data-shape="point"]').click();
await page.mouse.click(800, 450);
await page.waitForFunction(() => /^\d[\d,]* roads · \d[\d,]* intersections$/.test(document.querySelector('.selection-count')?.textContent || ''), null, { timeout: 60000 });
await waitForAnalytics();
results.spatialSelection = await page.locator('.selection-count').innerText();
results.selectedPerformance = await page.locator('.performance-total').first().innerText();
results.selectedTable = await page.locator('.drawer-handle').innerText();
await page.locator('.selection-tools button[data-shape="clear"]').click();
await waitForAnalytics();
await page.locator('.period-row select').nth(0).selectOption('2026');
await waitForAnalytics();
results.year2026Performance = await page.locator('.performance-total').first().innerText();
results.year2026Table = await page.locator('.drawer-handle').innerText();
await page.screenshot({ path: 'qa-hin-2026.png', fullPage: false });
await page.locator('.period-row select').nth(0).selectOption('2018');
await waitForAnalytics();
await page.locator('.toggle-row').nth(1).click();
await waitForAnalytics();
results.exclusiveLayerStates = await page.locator('.toggle-row').evaluateAll((nodes) => nodes.slice(0, 2).map((node) => ({ label: node.innerText.split('\n')[0], enabled: node.getAttribute('aria-pressed') })));
results.safetyPerformance = await page.locator('.performance').innerText();
results.safetyTable = await page.locator('.drawer-handle').innerText();
await page.screenshot({ path: 'qa-safety-network.png', fullPage: false });
await page.locator('.assignment-section select').selectOption('Segment');
await waitForAnalytics();
results.safetySegmentPerformance = await page.locator('.performance-total').first().innerText();
await page.locator('.assignment-section select').selectOption('Junction');
await waitForAnalytics();
results.safetyJunctionPerformance = await page.locator('.performance-total').first().innerText();
await page.locator('.assignment-section select').selectOption('All');
await waitForAnalytics();
await page.locator('.toggle-row').nth(1).click();
await waitForAnalytics();
await page.locator('.toggle-row').nth(2).click();
await page.waitForTimeout(3000);
await page.screenshot({ path: 'qa-crash-clusters.png', fullPage: false });
results.performance = await page.locator('.performance-total').first().innerText().catch(() => null);
results.analytics = await page.locator('.analytics-section').innerText().catch(() => null);
await page.locator('.analytics-section').screenshot({ path: 'qa-analytics.png' });
await page.locator('.left-panel nav button').nth(1).click();
results.filterText = await page.locator('.left-panel .panel-scroll').innerText();
await page.getByText('Distracted-driving crashes', { exact: true }).click();
await page.waitForTimeout(700);
await page.locator('.loading-block').waitFor({ state: 'detached', timeout: 60000 });
results.distractedPerformance = await page.locator('.performance-total').nth(1).innerText();
results.distractedSeverity = await page.locator('.chart-card').nth(1).innerText();
results.distractedOutcomes = await page.locator('.chart-card').nth(2).innerText();
await page.screenshot({ path: 'qa-desktop-distracted.png', fullPage: false });
await page.getByText('Reset filters', { exact: true }).click();
await page.waitForTimeout(700);
await page.locator('.loading-block').waitFor({ state: 'detached', timeout: 60000 });
await page.locator('.left-panel nav button').nth(0).click();
await page.locator('.mode-control button').nth(2).click();
await page.waitForTimeout(18000);
results.bicycleStatus = await page.locator('.status-button').textContent().catch(() => null);
results.bicyclePerformance = await page.locator('.performance-total').first().innerText().catch(() => null);
await page.screenshot({ path: 'qa-desktop-bicycle.png', fullPage: false });
await page.locator('.drawer-handle').click();
await page.waitForTimeout(800);
await page.locator('.table-wrap tbody tr').first().locator('button').click();
await page.waitForTimeout(3500);
results.networkPopup = await page.locator('.network-popup').innerText().catch(() => null);
await page.locator('.drawer-handle').click();
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'qa-mobile-map.png', fullPage: false });
await page.locator('.mobile-nav button').nth(1).click();
await page.waitForTimeout(600);
await page.screenshot({ path: 'qa-mobile-explore.png', fullPage: false });
await page.locator('.mobile-nav button').nth(2).click();
await page.waitForTimeout(600);
await page.locator('.analytics-section').scrollIntoViewIfNeeded();
await page.screenshot({ path: 'qa-mobile-insights.png', fullPage: false });
await browser.close();
console.log(JSON.stringify(results, null, 2));
